export const SEND_AUTOMATION_RETRY_BUDGET_MS = 75_000;
export const SEND_CONFIRMATION_TIMEOUT_MS = 5_000;
export const SEND_RESULT_SETTLEMENT_RESERVE_MS = 5_000;

export const SHUTDOWN_DRAIN_MS =
  SEND_AUTOMATION_RETRY_BUDGET_MS +
  SEND_CONFIRMATION_TIMEOUT_MS +
  SEND_RESULT_SETTLEMENT_RESERVE_MS;
export const SHUTDOWN_FORCE_EXIT_MS = SHUTDOWN_DRAIN_MS + 5_000;
export const RELAY_EXIT_TIMEOUT_SECONDS =
  SHUTDOWN_FORCE_EXIT_MS / 1_000 + 5;
export const RELAY_LAUNCHD_REMOVAL_TIMEOUT_MS =
  RELAY_EXIT_TIMEOUT_SECONDS * 1_000 + 5_000;
